### ISSUE TITLE
Manifest suggestions

### ISSUE THREAD

**Issue by AndrewBelt** [netboy3/MSM-vcvrack-plugin#2]
Just a suggestion to improve this module's information on https://library.vcvrack.com/MSM.

Modules are lacking descriptions, and it might be a good idea to set the author to "Phal-anx & netboy3" or whatever name you prefer.

**Comment by netboy3** [comment]
Hi Andrew,

I'm getting ready to release V2.0.0 (currently testing). I'll be adding module descriptions per your recommendation. Is your recommendation to modify the author above still stands considering the changes made recently to the licensing/code of ethics? I would love to have my dev-name attached less anonymously to my adopted plugins considering the amount of time I vested in them, but not if it breaks any rules.

**Comment by AndrewBelt** [comment]
A comma-separated list would look best. Use `"Phal-anx, netboy3"` for example. Or `&`. You can use your email if you want, since if Phal-anx has transferred the VCV Library role to you, they probably don't want to receive support emails.
