### ISSUE TITLE
Port to Rack V2

### ISSUE THREAD

**Issue by Torinbob** [netboy3/MSM-vcvrack-plugin#5]
Hi,

I was just wondering if you are planning to port the MSM modules to v2?

I love the Dual Delay in particular and forked your repo to see if I could get it up and running in V2. I managed to do it (with some help!) but for some reason we haven't managed to pin down the alternate png panels on the Treasure VCO were causing Rack v2 to crash on quit.

So for now i have commented those 2 panels out and otherwise everything seems to be working OK. I can send you a pull request if that would be useful?

Best,
Steve

**Comment by netboy3** [comment]
Hi Steve,

A bit busy IRL, but I'll have a little more time in a week or so to setup a new dev environment for V2 and get all my adopted modules re-imported.

**Comment by Torinbob** [comment]
That's great news, thank you.

**Comment by netboy3** [comment]
MSM has now been fully ported to Rack-V2. V2 binaries for Linux, Windows and Mac are available on the repo releases section and were built against Rack-SDK git version 219bbaf1. I've tested pretty extensively and all seems to be working fine. Please let me know if you discover any issues. Enjoy!
