### ISSUE TITLE
MSM Delay: clear buffer button

### ISSUE THREAD

**Issue by Eurikon** [netboy3/MSM-vcvrack-plugin#6]
Hi, and thanks again for porting the MSM plugin, this time for VCV Rack V2!

I was wondering if maybe the "buffer clear" buttons, could get a red color when active same as the red color on Valley Plateau buffer clear.

And to make the action visible when it is control by CV, right now they never show visual feedback.

**Comment by netboy3** [comment]
Added in commit cd599812cbaab6be164cc5a4adcae1abb6c34647
