### ISSUE TITLE
MSM delay: crashes hosting daw when used in VST

### ISSUE THREAD

**Issue by Eurikon** [netboy3/MSM-vcvrack-plugin#7]
Hi,

i just encountered the following, that i been able to replicate with several DAW hosts.

First create a new template for VCV Rack, a blank empty template with only MSM delay in it (i haven't checked the other MSM modules).
Save it as template for VCV. 

Close VCV

Open any daw, (i tested Ableton, Bitwig and Reason) , in the daw load VCV vst, it will crash the host.
Bitwig will sandbox the VST, the other 2 crashed.

**Comment by netboy3** [comment]
Thanks for the feedback. This is all very new. MSM was never tested inside a VST. It will take me some time to setup a proper VST testing environment.

**Comment by Eurikon** [comment]
Yeah i understand, i wish there was a trace in the log, but nothing in there.

**Comment by netboy3** [comment]
I verified the problem and believe I got it fixed. The following seems to be working well for me. Would you mind testing this and let me know if it's working well for you? Once testing is complete, I'll push the fix out.
Attached is a zip file, inside it are three plugins for each of the platforms.

- Close Rack2 (and the VST)
- Drop the proper vcvplugin file in the plugins folder inside your Rack2 user folder
- Delete the MSM folder in the plugins folder inside your Rack2 user folder.

[MSM-2.0.1.d.zip](https://github.com/netboy3/MSM-vcvrack-plugin/files/7636858/MSM-2.0.1.d.zip)

**Comment by cschol** [comment]
Your plugin stores references to custom fonts across frames. This leads to crashes in the VST when reloading a project.

Please see the following link on how to resolve this issue and re-submit to the Library:
https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames

**Comment by netboy3** [comment]
Yup. I'll push an update today.

**Comment by netboy3** [comment]
Fixed in commit 0f2cb2bc006625e8e464d5ea5ea50066ca93ae96
